name: Test

on: [push]

jobs:

  unit-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: pytest
        id: pytest
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: pytest
        continue-on-error: true

      # - name: Create issue on failure
      #   if: ${{ steps.pytest.outcome == 'failure' }}
      #   uses: JasonEtco/create-an-issue@v2
      #   with:
      #     title: "Test Failure: ${{ github.sha }}"
      #     body: |
      #       One or more tests failed in the build. Please check the workflow run for details:
      #       ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #     labels: bug
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ISSUE_TOKEN }}

      - name: Create GitHub Issue on Failure
        if: failure() && ${{ steps.pytest.outcome == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ISSUE_TOKEN }}
        run: |
          gh issue create \
            -t "Automated Test Failure" \
            -b "'pytest' step has failed
            
            *commit: ${{ github.sha }}*
            *committer: @${{ github.actor }}*
            
            Please investigate the issue. 

            Check the [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details." \
            -l "bug" \
            -a ${{ github.actor }}
        shell: bash
        continue-on-error: false
